customizations:
  cloudFormationStackSets: []
  cloudFormationStacks:
    # - name: IAM-Access-Analyzer
    #   description: Enables IAM Access Analyzer
    #   regions:
    #     - us-east-1
    #   deploymentTargets:
    #     organizationalUnits:
    #       - Security
    #   runOrder: 1
    #   template: ./cfn-templates/iam-analyzer.yaml
    #   terminationProtection: true
    - name: LZA-AWS-Config-Rules
      description: Enables Additional AWS Config Rules
      regions:
        - us-east-1
        - us-east-2
      deploymentTargets:
        organizationalUnits:
          - applications
          - galileo
          - pic-sure
          - Security
      runOrder: 1
      template: ./cfn-templates/config-rules.yml
      terminationProtection: true
    # - name: LZA-AWS-Config-Global-Rules
    #   description: Enables Additional AWS Config Rules
    #   regions:
    #     - us-east-1
    #     - us-east-2
    #   deploymentTargets:
    #     organizationalUnits:
    #       - Root
      # runOrder: 2
      # template: ./cfn-templates/config-rules-global.yml
      # terminationProtection: true
    # - name: LZA-RDS-S3-Integration-Role
    #   description: Enables RDS S3 Integration Role - Pauls
    #   regions:
    #     - us-east-1
    #   deploymentTargets:
    #     organizationalUnits:
    #       - pic-sure
    #   runOrder: 3
    #   template: ./cfn-templates/rds-s3-integration-role.yml
      # terminationProtection: true
    # - name: LZA-Avillach-Lab-instance-profile
    #   description: Enables Avillach Lab instance profile
    #   regions:
    #     - us-east-1
    #   deploymentTargets:
    #     organizationalUnits:
    #       - pic-sure
    #       - galileo
    #   runOrder: 4
    #   template: ./cfn-templates/avillach-lab-instance-profile.yml
    #   terminationProtection: true