AWSTemplateFormatVersion: 2010-09-09
Description: rds-s3-integration-role
Parameters:
  OrganizationName:
    Type: String

Resources:
  rdss3integrationrole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - rds.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: rds-s3-integration-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - 's3:ListBucket'
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:PutObjectAcl'
                  - 'secretsmanager:GetSecretValue'
                  - 'kms:DescribeKey'
                  - 'kms:Decrypt'
                  - 'kms:Encrypt'
                  - 'kms:GenerateDataKey'
                  - 'kms:GenerateDataKeyPair'

                Resource:
                  - 'arn:aws:secretsmanager:us-east-1:718952877825:secret:*'
                  - !Sub 'arn:aws:secretsmanager:us-east-1:${AWS::AccountId}:secret:*'
                  - 'arn:aws:kms:us-east-1:718952877825:key/*'   # kms cent
                  - 'arn:aws:kms:us-east-1:276175686361:key/*'   # kms pl
                  - 'arn:aws:kms:us-east-1:417090103303:key/*'   # kms hms
                  - !Sub 'arn:aws:kms:us-east-1:${AWS::AccountId}:key/*'
                  - !Sub 'arn:aws:s3:::avillach-*-etl'
                  - !Sub 'arn:aws:s3:::avillach-*-etl/*'

      RoleName: rds-s3-integration-role